Repository codeLabs-summer2021/3D-Model-World, pull requests merged in 2021-09, with the labels that each got.

#66 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/standard-issue.md
Labels: documentation, task

#65 README Overhaul
  README.md
Labels: documentation

#61 Local Storage
  index.css
  index.html
  index.js
  package-lock.json
  src/layers.js
  src/localStorage.js
  src/menu.js
  src/sketchfabIntegration.js
Labels: new feature

#64 Remove jQuery
  index.html
  index.js
  src/menu.js
Labels: task
